dist: trusty
notifications:
  email: false
language: java
jdk:
  - openjdk11

# command to build
install:
  - ./gradlew assemble
  - ./gradlew build
  - ./gradlew jar
  - ./gradlew javadoc

# command to run tests
script:
  - ./gradlew check

after_success: